name: Production Deployment

on:

  push:

    branches:

      - main

jobs:

  production:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Production Deploy

        run: |

          echo "Deploying Production"

          echo "Deployment Successful"


